{{- if .Values.kind.deployment | default false }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{ include "common.annotations" . | nindent 4 }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
  name: {{ include "application.fullname" . }}
spec:
  selector:
    matchLabels:
      {{ include "common.selectorLabels" . | nindent 6 }}
  {{- if not .Values.scaling.enabled }}
  replicas: {{ .Values.replicas | int }}
  {{- end }}
  minReadySeconds: {{ default 10 .Values.update.minReadySeconds }}
  template:
    metadata:
      labels:
        {{ include "common.labels" . | nindent 8 }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{ include "common.podAnnotations" . | nindent 8 }}
      {{- end }}
    spec:
      {{- if and .Values.serviceAccount .Values.serviceAccount.enabled }}
      serviceAccountName: {{ include "application.fullname" . }}
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ . | quote }}
      {{- end }}
      {{- if .Values.envFromFile.enabled }}
      volumes:
        {{ include "env.volumes" . | nindent 8  }}
      {{- end }}
      {{- with .Values.securityContent }}
      securityContext:
        {{- .toYaml . | nindent 8}}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        {{- include "application.container" . | nindent 8 }}
{{- end }}
