{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    {{ include "common.labels" . | nindent 4 }}
  annotations:
    {{ include "common.annotations" . | nindent 4 }}
  name: {{ include "application.fullname" . }}
spec:
  refreshInterval: {{ .Values.secrets.secretStore.refreshInterval | default "10s" }}
  secretStoreRef:
    name: {{ .Values.secrets.secretStore.name}}
    kind: {{ .Values.secrets.secretStore.kind }}
  {{- if .Values.envFromSecret.enabled }}
  dataFrom:
    {{ include "env.fromSecret" . | nindent 4 }}
  {{- end }}
  {{- if .Values.envFromFile.enabled }}
  data:
    {{ include "env.fromFile" . | nindent 4 }}
  {{- end }}
{{- end }}
