{{- if .Values.scaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    {{ include "common.annotations" . | nindent 4 }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
  name: {{ include "application.fullname" . }}
spec:
  maxReplicas: {{ .Values.scaling.replicas.max | default 1 }}
  minReplicas: {{ .Values.scaling.replicas.min | default 1 }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "application.fullname" . }}
  metrics:
    {{- if .Values.scaling.type.resource }}
    {{- if .Values.scaling.type.resource.memory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.scaling.type.resource.memory | default 80 }}
    {{- end }}
    {{- if .Values.scaling.type.resource.cpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.scaling.type.resource.cpu | default 80 }}
    {{- end }}
    {{- end }}
{{- end }}
