{{- if .Values.serviceAccount.enabled | default true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.annotations .Values.serviceAccount.roleArn }}
  annotations:
    {{- if .Values.serviceAccount.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
